name: 'LVZ Headline scraper'
description: 'Scrapes the Headlines of LVZ'
branding:
  icon: sliders
  color: purple
inputs:
  token:
    description: 'Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-t'
    - ${{ inputs.token }}
