name: 'Scrape Headlines'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Scraper
      id: scraper
      uses: DominikHerold/LVZHeadlines@main
      with:
        token: MySecret
      env:
        MY_SECRET: ${{ secrets.TOKEN_SECRET }}
    - uses: stefanzweifel/git-auto-commit-action@v4
